### ISSUE TITLE
Integrate YASGUI components

### ISSUE THREAD

**Issue by pchampin** [LinkedDataFragments/jQuery-Widget.js#4]
The client looks pretty good, but how about reusing components, such as those from the [YASGUI](http://doc.yasgui.org/) project? They are pretty cool too :)

Note that another way to look at it would be to implement LDT in YASGUI, as [suggested here](https://github.com/YASGUI/YASGUI/issues/47).

**Comment by mielvds** [comment]
It's on my development list since ISWC :) I'll try to squeeze it in soon.

**Comment by RubenVerborgh** [comment]
Would be great indeed! One thing I've discussed with YASGUI author @LaurensRietveld is the size of the code, which we should keep under control. However, there have been experiments for YASGUI to use the same SPARQL parser as the LDF client, which would substantially reduce the combined code size.

**Comment by LaurensRietveld** [comment]
Integrating both would be nice indeed!

Keeping the YASQE (I assume we are talking about YASQE here and not the whole YASGUI lib) size limited would be a nice-to-have as well. A few months ago I tried integrating the SPARQL.js parser into YASQE. This required quite some fiddling, as YASQE requires a tokenizer and shouldn't fail on invalid queries (something not directly applicable to sparql.js). My unfinished attempt was not a success: the responsiveness of YASQE decreased considerably after integration, but that was probably mostly caused by my fiddling around. 

Considering the expected decrease in JS size to be relatively small (70KB decrease in size), this issue moved a bit lower on my todo list (the main yasgui lib and the lodlaundromat has been the primary focus for the last few months)

**Comment by RubenVerborgh** [comment]
Alright, sounds like a plan then :smile:
@mielvds Let's briefly talk before this is started, as this repo should probably be cleaned up a bit before.

**Comment by LaurensRietveld** [comment]
And feel free to ping me as well, should you encounter YASQE-related issues

**Comment by mielvds** [comment]
I had a look at this recently, seems like a lot of CSS conflicts. Would require a careful isolation of the original css rules

**Comment by RubenVerborgh** [comment]
In the meantime, this repo has been cleaned up and is in good shape for extensions.

**Comment by akuckartz** [comment]
:+1:

Any news ? :-)

**Comment by mielvds** [comment]
I'll take another look soon

**Comment by mielvds** [comment]
We will move this issue to a new version of the client.
