### ISSUE TITLE
Update problem. Missing repo?

### ISSUE THREAD

**Issue by cKlee** [LinkedDataFragments/jQuery-Widget.js#7]
I cannot update via ```npm update``` or ```npm install```. Either my SSH connection fails (but HTTPS fails before silently) or the repo rubenverborgh/follow-redirects.git is missing.

```
547 error Linux 3.2.0-4-amd64
548 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
549 error node v5.10.1
550 error npm  v3.8.7
551 error code 128
552 error Command failed: gitx clone --template=/srv/zdb/prod/.npm/_git-remotes/_templates --mirror git@github.com:rubenverborgh/follow-redirects.git /srv/zdb/prod/.npm/_git-remotes/git-github-com-rubenverborgh-follow-redirects-git-feature-requestproxy-27e836fb
552 error Klone in Bare-Repository '/srv/zdb/prod/.npm/_git-remotes/git-github-com-rubenverborgh-follow-redirects-git-feature-requestproxy-27e836fb' ...
552 error ssh: connect to host ssh.github.com port 443: Connection timed out
552 error fatal: Could not read from remote repository.
```

**Comment by RubenVerborgh** [comment]
I'm not sure why your connection times out to port ssh.github.com:443, but that actually shouldn't be a problem, since:

- you don't actually need follow-redirects for the browser version
- I've updated the follow-redirects package to include the patch from my fork; the current develop of the LDF Client [depends on follow-redirects 1.0.0](https://github.com/LinkedDataFragments/Client.js/commit/7ecff3928dca0ff8588ae96854f247f0633644f8) instead of my fork.

**Comment by cKlee** [comment]
SSH seems to be a fallback when HTTPS fails. Because I'm behind a proxy, ssh times out and the whole install procedure dies. But I edited the package.json:

```json
"dependencies": {
    "ldf-client": "LinkedDataFragments/Client.js#develop",
    "n3": "^0.8.1"
  }
```

and this works for me.

Thanks!
